WARNING 2016-03-12 08:17:49,087 base 92690 4407758848 Not Found: /
WARNING 2016-03-12 08:17:52,786 views 92690 4413014016 heyheyhey
WARNING 2016-03-12 08:36:49,774 views 95134 4452233216 heyheyhey
WARNING 2016-03-12 08:36:51,249 views 95134 4457488384 heyheyhey
WARNING 2016-03-19 05:10:50,315 base 48697 4563595264 Not Found: /
WARNING 2016-03-19 05:10:55,230 base 48697 4563595264 Not Found: /photos/1
WARNING 2016-03-19 05:14:04,950 base 48697 4563595264 Not Found: /accounts/login/
WARNING 2016-03-19 05:14:10,083 base 48697 4563595264 Not Found: /accounts/login/
WARNING 2016-03-19 05:16:08,799 base 48697 4569899008 Not Found: /admin/photos/1
WARNING 2016-03-19 05:16:13,751 base 48697 4575154176 Not Found: /photos/1
ERROR 2016-03-19 05:16:13,765 base 48697 4580409344 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'my_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'my_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
ERROR 2016-03-19 05:28:28,741 base 51127 4443299840 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'my_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'my_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
ERROR 2016-03-19 05:28:30,319 base 51127 4448555008 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'my_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'my_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
WARNING 2016-03-19 05:28:33,404 base 51127 4453810176 Not Found: /photos/2
ERROR 2016-03-19 05:28:33,417 base 51127 4443688960 Internal Server Error: /photos/2/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'my_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'my_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
ERROR 2016-03-19 05:28:46,308 base 51212 4548476928 Internal Server Error: /photos/2/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'my_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'my_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
ERROR 2016-03-19 05:29:11,392 base 51212 4548476928 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'my_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'my_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
ERROR 2016-03-19 05:29:21,443 base 51280 4531085312 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'my_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'my_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
ERROR 2016-03-19 05:29:51,756 base 51326 4382650368 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'my_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'my_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
ERROR 2016-03-19 05:30:03,016 base 51344 4417384448 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'my_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'my_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
ERROR 2016-03-19 05:30:13,221 base 51362 4597219328 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'my_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'my_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
ERROR 2016-03-19 05:30:28,106 base 51390 4428374016 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1132, in find_library
    return parser.libraries[name]
KeyError: 'my_tags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1189, in load
    lib = find_library(parser, name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1136, in find_library
    name, "\n".join(sorted(parser.libraries.keys())),
django.template.exceptions.TemplateSyntaxError: 'my_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_static
admin_urls
cache
future
i18n
l10n
log
static
staticfiles
tz
ERROR 2016-03-19 05:40:50,746 base 52843 4424876032 Internal Server Error: /photos/1/like/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 60, in like_photo
    if is_created is False:
NameError: name 'is_created' is not defined
ERROR 2016-03-19 05:43:29,745 base 53208 4366286848 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 177, in translate_token
    op = OPERATORS[token]
KeyError: 'photo|did_like:request.user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 959, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 168, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 179, in translate_token
    return self.create_var(token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 962, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 601, in compile_filter
    return FilterExpression(token, self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 695, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 607, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'did_like'
ERROR 2016-03-19 05:43:36,161 base 53208 4366286848 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 177, in translate_token
    op = OPERATORS[token]
KeyError: 'photo|did_like:request.user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 959, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 168, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 179, in translate_token
    return self.create_var(token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 962, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 601, in compile_filter
    return FilterExpression(token, self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 695, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 607, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'did_like'
ERROR 2016-03-19 05:43:48,047 base 53234 4532953088 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 177, in translate_token
    op = OPERATORS[token]
KeyError: 'photo|did_like:request.user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 959, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 168, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 179, in translate_token
    return self.create_var(token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 962, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 601, in compile_filter
    return FilterExpression(token, self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 695, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 607, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'did_like'
ERROR 2016-03-19 05:44:12,296 base 53287 4528386048 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 177, in translate_token
    op = OPERATORS[token]
KeyError: 'photo|did_like:request.user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 959, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 168, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 179, in translate_token
    return self.create_var(token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 962, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 601, in compile_filter
    return FilterExpression(token, self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 695, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 607, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'did_like'
ERROR 2016-03-19 05:44:38,487 base 53287 4528386048 Internal Server Error: /photos/1/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 177, in translate_token
    op = OPERATORS[token]
KeyError: 'photo|did_like:request.user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 44, in view_photo
    return render(request, 'view_photo.html', ctx)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 96, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loader.py", line 32, in get_template
    return engine.get_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/backends/django.py", line 40, in get_template
    return Template(self.engine.get_template(template_name, dirs), self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/engine.py", line 157, in find_template
    name, template_dirs=dirs, skip=skip,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/loaders/base.py", line 46, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 189, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 231, in compile_nodelist
    return parser.parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 516, in parse
    raise self.error(token, e)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 514, in parse
    compiled_result = compile_func(self, token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 1027, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 959, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 168, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/smartif.py", line 179, in translate_token
    return self.create_var(token)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/defaulttags.py", line 962, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 601, in compile_filter
    return FilterExpression(token, self)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 695, in __init__
    filter_func = parser.find_filter(filter_name)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/template/base.py", line 607, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'did_like'
ERROR 2016-03-19 05:46:29,306 base 53638 4398989312 Internal Server Error: /photos/1/like/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 60, in like_photo
    if is_created is False:
NameError: name 'is_created' is not defined
ERROR 2016-03-19 05:47:46,826 base 53849 4432539648 Internal Server Error: /photos/1/like/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/views.py", line 70, in like_photo
    return redirect('photos:view_photo', kwargs={'pk': photo.pk})
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 116, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/shortcuts.py", line 204, in resolve_url
    return urlresolvers.reverse(to, args=args, kwargs=kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/urlresolvers.py", line 600, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/urlresolvers.py", line 508, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'view_photo' with arguments '()' and keyword arguments '{'kwargs': {'pk': 1}}' not found. 1 pattern(s) tried: ['photos/(?P<pk>[0-9]+)/$']
WARNING 2016-03-19 06:08:38,040 base 56790 4461072384 Not Found: /admin
WARNING 2016-03-19 08:30:00,543 base 77935 4591403008 Not Found: /photos/1
WARNING 2016-03-19 08:30:06,914 base 77935 4591403008 Not Found: /admin
ERROR 2016-03-19 08:31:44,742 base 77935 4591665152 Internal Server Error: /admin/photos/photo/add/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1378, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 991, in save_model
    obj.save()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/models.py", line 20, in make_thumbnail_image
    make_thumbnail(instance.image.path, 80,80)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/taskqueue.py", line 22, in make_thumbnail
    im.thubnail((width, height,), Image.ANTIALAIS)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/PIL/Image.py", line 628, in __getattr__
    raise AttributeError(name)
AttributeError: thubnail
WARNING 2016-03-19 08:32:32,213 base 78241 4493926400 Not Found: /admin
ERROR 2016-03-19 08:32:44,033 base 78241 4494712832 Internal Server Error: /admin/photos/photo/add/
Traceback (most recent call last):
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1437, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 1378, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/contrib/admin/options.py", line 991, in save_model
    obj.save()
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/db/models/base.py", line 737, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/photos/models.py", line 20, in make_thumbnail_image
    make_thumbnail(instance.image.path, 80,80)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/Users/1002472/helloworld/hwenv/lib/python3.4/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/Users/1002472/helloworld/hwenv/helloworld/pystagram/taskqueue.py", line 22, in make_thumbnail
    im.thumbnail((width, height,), Image.ANTIALAIS)
AttributeError: 'module' object has no attribute 'ANTIALAIS'
WARNING 2016-03-26 05:31:11,572 base 74155 4597903360 Not Found: /admin
WARNING 2016-03-26 05:32:18,699 base 74155 4598444032 Not Found: /pystagram
WARNING 2016-03-26 05:32:42,796 base 74155 4598444032 Not Found: /photos
WARNING 2016-03-26 05:32:42,803 views 74155 4603961344 the toppage view is called
